Models/ErrorViewModel.cs
using System;

namespace ProdutosComprados.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Produtos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProdutosComprados.Models
{
    public class Produtos
    {
        [Key]
        public int ListaDeProdutosId { get; set; }
        public string NomeProduto { get; set; }
        public double PrecoProduto { get; set; }
        //public double? TotalProduto { get; set; }
        public bool ProdutoComprado { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProdutosComprados.Models;

namespace ProdutosComprados.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProdutosComprados.Data;
using ProdutosComprados.Models;
using Highsoft.Web.Mvc.Charts;

namespace ProdutosComprados.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly ProdutosCompradosContext _context;

        public ProdutosController(ProdutosCompradosContext context)
        {
            _context = context;
        }

        // GET: Produtos
        public async Task<IActionResult> Index(string ProdutoComprado)
        {
            List<Produtos> produtos = new List<Produtos>();

            ViewBag.Comprado = new SelectList(Comprado(), ProdutoComprado);

            produtos = _context.Produtos.Where(x => x.ListaDeProdutosId > 0).ToList();

            List<ColumnSeriesData> PrecoData = new List<ColumnSeriesData>();
            List<LineSeriesData> TotalPreco = new List<LineSeriesData>();

            //produtos = _context.Produtos.Where(x => x.NomeProduto != "").ToList();
            produtos.ForEach(p => PrecoData.Add(new ColumnSeriesData { Y = p.PrecoProduto }));
            List<string> precoDataString = new List<string>();
            produtos.ForEach(p => precoDataString.Add(p.NomeProduto));
            List<double> totalPreco = new List<double>();
            double soma = 0.0;
            //produtos.ForEach(p => TotalPreco.Add(new LineSeriesData { Y = p.PrecoProduto }));
            foreach (var item in produtos)
            {
                soma += item.PrecoProduto;
                TotalPreco.Add(new LineSeriesData { Y = Math.Round(soma, 2)});
            }



            ViewData["PrecoData"] = PrecoData;
            ViewData["PrecoDataString"] = precoDataString;
            ViewData["TotalPreco"] = TotalPreco;

            if (ProdutoComprado == "Sim")
            {
                //var comprados = _context.Produtos.Where(x => x.ProdutoComprado == true).ToList();
                produtos = _context.Produtos.Where(x => x.ProdutoComprado == true).ToList();
                return View(produtos);
            }
            else if (ProdutoComprado == "Não")
            {
                produtos = _context.Produtos.Where(x => x.ProdutoComprado == false).ToList();
                return View(produtos);
            }

            //List<ColumnSeriesData> PrecoData = new List<ColumnSeriesData>();

            //produtos = _context.Produtos.Where(x => x.NomeProduto != "").ToList();
            //produtos.ForEach(p => PrecoData.Add( new ColumnSeriesData { Y = p.PrecoProduto }));
            //List<string> precoDataString = new List<string>();
            //produtos.ForEach(p => precoDataString.Add(p.NomeProduto));
            //ViewData["PrecoData"] = PrecoData;
            //ViewData["PrecoDataString"] = precoDataString;


            return View(await _context.Produtos.ToListAsync());
        }

        private List<string> Comprado()
        {
            List<string> comprado = new List<string>
            {
                "Sim","Não"
            };

            return comprado;
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtos = await _context.Produtos
                .FirstOrDefaultAsync(m => m.ListaDeProdutosId == id);
            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ListaDeProdutosId,NomeProduto,PrecoProduto,ProdutoComprado")] Produtos produtos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produtos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produtos);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtos = await _context.Produtos.FindAsync(id);
            if (produtos == null)
            {
                return NotFound();
            }
            return View(produtos);
        }

        // POST: Produtos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ListaDeProdutosId,NomeProduto,PrecoProduto,ProdutoComprado")] Produtos produtos)
        {
            if (id != produtos.ListaDeProdutosId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produtos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutosExists(produtos.ListaDeProdutosId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produtos);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtos = await _context.Produtos
                .FirstOrDefaultAsync(m => m.ListaDeProdutosId == id);
            if (produtos == null)
            {
                return NotFound();
            }

            return View(produtos);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produtos = await _context.Produtos.FindAsync(id);
            _context.Produtos.Remove(produtos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutosExists(int id)
        {
            return _context.Produtos.Any(e => e.ListaDeProdutosId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Produtos/Create.cshtml
@model ProdutosComprados.Models.Produtos

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeProduto" class="control-label"></label>
                <input asp-for="NomeProduto" class="form-control" />
                <span asp-validation-for="NomeProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoProduto" class="control-label"></label>
                <input asp-for="PrecoProduto" class="form-control" />
                <span asp-validation-for="PrecoProduto" class="text-danger"></span>
            </div>
            @*<div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ProdutoComprado" /> @Html.DisplayNameFor(model => model.ProdutoComprado)
                </label>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Produtos/Delete.cshtml
@model ProdutosComprados.Models.Produtos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeProduto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeProduto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecoProduto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecoProduto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoComprado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoComprado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ListaDeProdutosId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Produtos/Details.cshtml
@model ProdutosComprados.Models.Produtos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produtos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomeProduto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomeProduto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecoProduto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecoProduto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdutoComprado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProdutoComprado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ListaDeProdutosId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Produtos/Edit.cshtml
@model ProdutosComprados.Models.Produtos

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produtos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ListaDeProdutosId" />
            <div class="form-group">
                <label asp-for="NomeProduto" class="control-label"></label>
                <input asp-for="NomeProduto" class="form-control" />
                <span asp-validation-for="NomeProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoProduto" class="control-label"></label>
                <input asp-for="PrecoProduto" class="form-control" />
                <span asp-validation-for="PrecoProduto" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ProdutoComprado" /> @Html.DisplayNameFor(model => model.ProdutoComprado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Produtos/Index.cshtml
@model IEnumerable<ProdutosComprados.Models.Produtos>
@using Highsoft.Web.Mvc.Charts
@using Highsoft.Web.Mvc.Charts.Rendering

@{
    ViewData["Title"] = "Index";
}

<div class="col-md-12 panel panel-default">
    <div>
        @using (Html.BeginForm("Index", "Produtos", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="container">
                <div class="col-md-6">
                    <p style="font-size: 30px">Produto:</p>
                    @Html.DropDownList("ProdutoComprado", (IEnumerable<SelectListItem>)ViewBag.Comprado, string.Empty, htmlAttributes: new { @class = "form-control" })
                </div>
                <div class="col-md-6">
                    <br />
                    <input class="col-md-3 btn btn-dark" type="submit" value="Filtrar" />
                </div>
            </div>
        }
    </div>
    <div class="col-md-12">
        <br />
    </div>
</div>

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeProduto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecoProduto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProdutoComprado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeProduto)
                </td>
                <td class="PrecoProduto">
                    @Html.DisplayFor(modelItem => item.PrecoProduto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProdutoComprado)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ListaDeProdutosId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ListaDeProdutosId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ListaDeProdutosId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <h1>Valor Total:</h1>
    <h5>R$ <b id="totalProdutos"></b></h5>
    <h3>Parcelas</h3>
    <select id="parcelas" onChange="update()">
        <option value="1">1x</option>
        <option value="2">2x</option>
        <option value="3">3x</option>
        <option value="4">4x</option>
        <option value="5">5x</option>
        <option value="6">6x</option>
        <option value="7">7x</option>
        <option value="8">8x</option>
        <option value="9">9x</option>
        <option value="10">10x</option>
        <option value="11">11x</option>
        <option value="12">12x</option>
    </select>
    <input type="text" id="value" readonly>
</div>




<div>
    @{ var chartOptions = new Highcharts
        {
            Title = new Title
            {
                Text = "Valores dos Produtos Adicionados na Lista de Compras"
            },
            Subtitle = new Subtitle
            {
                Text = "Todos os Valores dos Produtos"
            },
            XAxis = new List<XAxis>
            {
                new XAxis
                {
                    Categories = ViewData["PrecoDataString"] as List<string>
                    //Categories = new List<string>
                    //{
                        
                    //    //data = ViewData["PrecoDataString"] as List<string>
                    //    //"Produto 1",
                    //    //"Produto 2",
                    //    //"Produto 3",
                    //    //"Produto 4",
                    //    //"Produto 5",
                    //    //"Produto 6",
                    //    //"Produto 7",
                    //    //"Produto 8",
                    //    //"Produto 9",
                    //    //"Produto 10",
                    //    //"Produto 11",
                    //    //"Produto 12"
                    //}
                }
            },
            YAxis = new List<YAxis>
            {
                new YAxis
                {
                    Min = 0,
                    Title = new YAxisTitle
                    {
                        Text = "Valores R$"
                    }
                }
            },
            Tooltip = new Tooltip
            {
                Shared = true,
                UseHTML = true
            },
            PlotOptions = new PlotOptions
            {
                Column = new PlotOptionsColumn
                {
                    PointPadding = 0.2,
                    BorderWidth = 0,
                    Animation = new Animation { Enabled = false }
                }
            },
            Series = new List<Series>
            {
                new ColumnSeries
                {
                    Name = "Produtos",
                    Data = ViewData["PrecoData"] as List<ColumnSeriesData>
                },
                new LineSeries
                {
                    Name = "Valor Total",
                    Data = ViewData["TotalPreco"] as List<LineSeriesData>
                }
            }
        };
        chartOptions.ID = "chart";
        var renderer = new HighchartsRenderer(chartOptions);
    }
    @Html.Raw(renderer.RenderHtml())
</div>



<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script>

    //funcionando
    var preco = document.querySelectorAll(".PrecoProduto");
    console.log(preco);
    var auxSoma = 0;

    //A propriedade textContent da interface Node representa o
    //conteúdo de texto de um nó e dos seus descendentes.
    //Nota: textContent e HTMLElement.innerText são facilmente confundidos,
    //mas os dois possuem importantes diferenças entre sí.
    for (let i = 0; i <= preco.length; i++) {
        let valor = parseFloat(preco[i].textContent.replace(',', '.'));
        console.log('valor ' + valor);
        auxSoma += valor;
        console.log('x ' + auxSoma);
        document.getElementById('totalProdutos').innerText = auxSoma.toFixed(2).replace('.', ',');
    }

    function update() {
        var select = document.getElementById('parcelas');
        var option = select.options[select.selectedIndex];
        var totalProduto = document.getElementById('totalProdutos').innerText;

        var valorParcela = ((totalProduto.replace(',', '.')) / option.value).toFixed(2).replace('.', ',');

        var prestacao = document.getElementById('value').value = 'R$' + valorParcela;

        console.log(prestacao);
    }

    update();
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProdutosComprados</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProdutosComprados</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProdutosComprados - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>